-- Case: Không hỗ trợ UNCOMMITED / REPEATABLE READ, Chạy thử ở bất kỳ session.
ROLLBACK;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

ROLLBACK;
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;

ROLLBACK;


-- Lost Update
ALTER SESSION SET ISOLATION_LEVEL = READ COMMITTED;

SELECT * 
FROM KHOSANPHAM_QLKHO
WHERE MASANPHAM = 'SP00028';

UPDATE KHOSANPHAM_QLKHO
SET SOLUONG = 90, NGAYCAPNHAT = SYSDATE
WHERE MASANPHAM = 'SP00028';

COMMIT;

SELECT * 
FROM KHOSANPHAM_QLKHO
WHERE MASANPHAM = 'SP00028';

-- Fix
ALTER SESSION SET ISOLATION_LEVEL = SERIALIZABLE;

SELECT MASANPHAM, MACHINHANH, SOLUONG 
FROM KHOSANPHAM_QLKHO
WHERE MASANPHAM = 'SP00028';

UPDATE KHOSANPHAM_QLKHO
SET SOLUONG = 80, NGAYCAPNHAT = SYSDATE
WHERE MASANPHAM = 'SP00028';

COMMIT;

SELECT * 
FROM KHOSANPHAM_QLKHO
WHERE MASANPHAM = 'SP00028';


-- Non - Repeatable Read
INSERT INTO DONHANG (
    MADONHANG,
    MAKHACHHANG,
    MANHANVIEN,
    TONGTIEN,
    NGAYTAO,
    PHUONGTHUCTHANHTOAN
)
VALUES (
    'DH-DEMO-NRR-001',
    'KH02401',
    'NV00842',
    10000000,
    SYSDATE,
    N'Ví MoMo'
);

COMMIT;


ALTER SESSION SET ISOLATION_LEVEL = READ COMMITTED;

SELECT * 
FROM DONHANG
WHERE MADONHANG = 'DH-DEMO-NRR-001';

SELECT MADONHANG, TONGTIEN
FROM DONHANG 
WHERE MADONHANG = 'DH-DEMO-NRR-001'; 

-- Fix
ALTER SESSION SET ISOLATION_LEVEL = SERIALIZABLE;

SELECT * 
FROM DONHANG
WHERE MADONHANG = 'DH-DEMO-NRR-001';

SELECT MADONHANG, TONGTIEN
FROM DONHANG 
WHERE MADONHANG = 'DH-DEMO-NRR-001'; 

COMMIT;

SELECT MADONHANG, TONGTIEN
FROM DONHANG 
WHERE MADONHANG = 'DH-DEMO-NRR-001';


-- Phantom Read
ALTER SESSION SET ISOLATION_LEVEL = READ COMMITTED;

SELECT COUNT(*) AS SO_DON_HANG_LON 
FROM DONHANG 
WHERE TONGTIEN >= 50000000;

SELECT COUNT(*) AS SO_DON_HANG_LON 
FROM DONHANG 
WHERE TONGTIEN >= 50000000;

-- Fix
ALTER SESSION SET ISOLATION_LEVEL = SERIALIZABLE;

SELECT COUNT(*) AS SO_DON_HANG_LON 
FROM DONHANG 
WHERE TONGTIEN >= 50000000;

SELECT COUNT(*) AS SO_DON_HANG_LON 
FROM DONHANG 
WHERE TONGTIEN >= 50000000;

COMMIT;

SELECT COUNT(*) AS SO_DON_HANG_LON 
FROM DONHANG 
WHERE TONGTIEN >= 50000000;


-- Deadlock
ALTER SESSION SET ISOLATION_LEVEL = READ COMMITTED;

UPDATE KHOSANPHAM_QLKHO
SET SOLUONG = SOLUONG - 1, NGAYCAPNHAT = SYSDATE 
WHERE MASANPHAM = 'SP00028';

UPDATE KHOSANPHAM_QLBANHANG
SET TONGSLDABAN = TONGSLDABAN + 1, NGAYCAPNHAT = SYSDATE
WHERE MASANPHAM = 'SP00028';

ROLLBACK;