-- Thực thi tại Site 3 với quyền NhanVien
WITH ALL_ORDERS_DISTRIBUTED AS (
-- Site 3: Miền Trung - dữ liệu local
    SELECT MAKHACHHANG, PHUONGTHUCTHANHTOAN, N'Miền Trung' AS VUNG_MIEN
    FROM CN3.DONHANG
    
    UNION ALL
    
-- Site 1: Miền Nam - dữ liệu qua DB Link từ Site 3 sang Site 1
    SELECT MAKHACHHANG, PHUONGTHUCTHANHTOAN, N'Miền Nam' AS VUNG_MIEN
    FROM CN1.DONHANG@nv3_to_nv1
    
    UNION ALL
    
-- Site 2: Miền Bắc - dữ liệu qua DB Link từ Site 3 sang Site 2
    SELECT MAKHACHHANG, PHUONGTHUCTHANHTOAN, N'Miền Bắc' AS VUNG_MIEN
    FROM CN2.DONHANG@nv3_to_nv2
)
SELECT VUNG_MIEN, PHUONGTHUCTHANHTOAN, COUNT(DISTINCT MAKHACHHANG) AS SO_LUONG_KHACH_THUC_TE, COUNT(*) AS TONG_SO_LUOT_GIAO_DICH
FROM ALL_ORDERS_DISTRIBUTED
GROUP BY VUNG_MIEN, PHUONGTHUCTHANHTOAN
HAVING COUNT(DISTINCT MAKHACHHANG) > 500
ORDER BY VUNG_MIEN ASC, SO_LUONG_KHACH_THUC_TE DESC;
/


-- Thực thi tại Site 3 với quyền NhanVien
WITH ALL_EMPLOYEE_SALES AS (
    -- Site 3: Miền Trung - dữ liệu local
    SELECT MANHANVIEN, TONGTIEN, N'Miền Trung' AS VUNG_MIEN
    FROM CN3.DONHANG

    UNION ALL

    -- Site 1: Miền Nam - dữ liệu qua DB Link từ Site 3 sang Site 1
    SELECT MANHANVIEN, TONGTIEN, N'Miền Nam' AS VUNG_MIEN
    FROM CN1.DONHANG@nv3_to_nv1

    UNION ALL

    -- Site 2: Miền Bắc - dữ liệu qua DB Link từ Site 3 sang Site 2
    SELECT MANHANVIEN, TONGTIEN, N'Miền Bắc' AS VUNG_MIEN
    FROM CN2.DONHANG@nv3_to_nv2
),

SALES_BY_EMPLOYEE AS (
    -- Gom doanh số theo từng nhân viên ở từng vùng
    SELECT VUNG_MIEN, MANHANVIEN, SUM(TONGTIEN) AS DOANH_SO_NHAN_VIEN
    FROM ALL_EMPLOYEE_SALES
    GROUP BY VUNG_MIEN, MANHANVIEN
),

BRANCH_STATS AS (
    -- Tính doanh số cao nhất, thấp nhất và trung bình của từng vùng
    SELECT VUNG_MIEN, MAX(DOANH_SO_NHAN_VIEN) AS DOANH_SO_CAO_NHAT, MIN(DOANH_SO_NHAN_VIEN) AS DOANH_SO_THAP_NHAT, AVG(DOANH_SO_NHAN_VIEN) AS DOANH_SO_TRUNG_BINH
    FROM SALES_BY_EMPLOYEE
    GROUP BY VUNG_MIEN
),

TOP_EMPLOYEE AS (
    -- Xếp hạng nhân viên theo doanh số trong từng vùng
    SELECT VUNG_MIEN, MANHANVIEN, DOANH_SO_NHAN_VIEN, RANK() OVER (
            PARTITION BY VUNG_MIEN
            ORDER BY DOANH_SO_NHAN_VIEN DESC
        ) AS XEP_HANG
    FROM SALES_BY_EMPLOYEE
)

SELECT
    te.VUNG_MIEN,
    te.MANHANVIEN AS NHAN_VIEN_DOANH_SO_CAO_NHAT,
    TO_CHAR(te.DOANH_SO_NHAN_VIEN, '999,999,999,999') || ' VND' AS DOANH_SO_CAO_NHAT,
    TO_CHAR(bs.DOANH_SO_THAP_NHAT, '999,999,999,999') || ' VND' AS DOANH_SO_THAP_NHAT,
    TO_CHAR(ROUND(bs.DOANH_SO_TRUNG_BINH, 2), '999,999,999,999') || ' VND' AS DOANH_SO_TRUNG_BINH,
    TO_CHAR(
        ROUND(te.DOANH_SO_NHAN_VIEN - bs.DOANH_SO_TRUNG_BINH, 2),
        '999,999,999,999'
    ) || ' VND' AS CHENH_LECH_SO_VOI_TRUNG_BINH
FROM TOP_EMPLOYEE te
JOIN BRANCH_STATS bs
    ON te.VUNG_MIEN = bs.VUNG_MIEN
WHERE te.XEP_HANG = 1
ORDER BY te.DOANH_SO_NHAN_VIEN DESC;
/

